# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prices_provisional",
                    models.BooleanField(
                        default=True,
                        help_text="Toont 'Voorlopige prijzen' op de prijzenpagina.",
                        verbose_name="prijzen als voorlopig tonen",
                    ),
                ),
                (
                    "guest_data_retention_days",
                    models.PositiveIntegerField(
                        default=90,
                        verbose_name="gastgegevens bewaren (dagen na einde beschikbaarheid)",
                    ),
                ),
                (
                    "anonymous_draft_retention_days",
                    models.PositiveIntegerField(
                        default=30,
                        verbose_name="ontwerpen zonder account bewaren (dagen)",
                    ),
                ),
                (
                    "unpaid_draft_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        verbose_name="onbetaalde concepten van klanten bewaren (dagen)",
                    ),
                ),
                (
                    "default_max_party_size",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="standaard max. personen per aanmelding"
                    ),
                ),
                (
                    "support_response_text",
                    models.CharField(
                        blank=True,
                        help_text="Alleen invullen als je deze belofte echt kunt waarmaken, bijv. 'We reageren binnen 2 werkdagen.'",
                        max_length=160,
                        verbose_name="tekst over reactietijd",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "instellingen",
                "verbose_name_plural": "instellingen",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="naam")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mailadres"),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("vraag", "Algemene vraag"),
                            ("bestelling", "Vraag over een bestelling"),
                            ("maatwerk", "Bijzondere wens of maatwerk"),
                            ("zakelijk", "Zakelijke samenwerking"),
                        ],
                        default="vraag",
                        max_length=20,
                        verbose_name="onderwerp",
                    ),
                ),
                ("message", models.TextField(max_length=4000, verbose_name="bericht")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contactbericht",
                "verbose_name_plural": "contactberichten",
                "ordering": ["-created_at"],
            },
        ),
    ]
