# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        ("orders", "0001_initial"),
        ("wishes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_key",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("kind", models.CharField(blank=True, max_length=40)),
                ("to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "In wachtrij"),
                            ("sent", "Verzonden"),
                            ("test", "Testmodus: bewaard, niet verzonden"),
                            ("failed", "Mislukt"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attach_qr_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "custom_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="wishes.customrequest",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "uitgaande e-mail",
                "verbose_name_plural": "uitgaande e-mails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "unique_key",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wacht"),
                            ("running", "Bezig"),
                            ("done", "Klaar"),
                            ("failed", "Mislukt, wordt opnieuw geprobeerd"),
                            ("dead", "Mislukt, handmatige actie nodig"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=6)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "verwerkingstaak",
                "verbose_name_plural": "verwerkingstaken",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"],
                        name="processing__status_50dea1_idx",
                    )
                ],
            },
        ),
    ]
