# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=60, verbose_name="naam")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="omschrijving"
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(verbose_name="prijs (centen)"),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        help_text="Bijv. music, gallery, story",
                        max_length=40,
                        verbose_name="ontgrendelt functie",
                    ),
                ),
                (
                    "extra_months",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="extra maanden online"
                    ),
                ),
                (
                    "gallery_photos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="foto's in galerij"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="volgorde"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "extra optie",
                "verbose_name_plural": "extra opties",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=60, verbose_name="naam")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="omschrijving"
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(verbose_name="prijs (centen)"),
                ),
                (
                    "availability_months",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="maanden online"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=list, verbose_name="inbegrepen functies"
                    ),
                ),
                (
                    "max_gallery_photos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="max. foto's in galerij"
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="punten op de prijzenpagina",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="uitgelicht"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="volgorde"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pakket",
                "verbose_name_plural": "pakketten",
                "ordering": ["sort_order", "price_cents"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=80, verbose_name="naam")),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="korte omschrijving"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="beschrijving"),
                ),
                (
                    "style_notes",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="stijlrichting"
                    ),
                ),
                (
                    "occasions",
                    models.JSONField(default=list, verbose_name="gelegenheden"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="zichtbaar en bestelbaar"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="volgorde"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ontwerp",
                "verbose_name_plural": "ontwerpen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="versie")),
                (
                    "renderer",
                    models.CharField(
                        help_text="Bijv. liefde-op-papier/v1",
                        max_length=120,
                        verbose_name="map",
                    ),
                ),
                ("manifest", models.JSONField(default=dict)),
                ("changelog", models.TextField(blank=True, verbose_name="wijzigingen")),
                (
                    "released_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="uitgebracht"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "ontwerpversie",
                "verbose_name_plural": "ontwerpversies",
                "ordering": ["template", "-number"],
            },
        ),
        migrations.AddField(
            model_name="template",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.templateversion",
                verbose_name="versie voor nieuwe uitnodigingen",
            ),
        ),
        migrations.AddConstraint(
            model_name="templateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "number"), name="uniq_template_version"
            ),
        ),
    ]
