# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
import django.utils.timezone
import invitations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("bruiloft", "Bruiloft"),
                            ("verloving", "Verloving"),
                            ("verjaardag", "Verjaardag"),
                            ("jubileum", "Jubileum"),
                            ("babyshower", "Babyshower"),
                            ("zakelijk", "Zakelijk evenement"),
                        ],
                        max_length=20,
                        verbose_name="gelegenheid",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="titel"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=90,
                        null=True,
                        unique=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Concept"),
                            ("paid", "Betaald, wordt verwerkt"),
                            ("live", "Online"),
                            ("offline", "Offline gehaald"),
                            ("expired", "Verlopen"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("draft_content", models.JSONField(default=dict)),
                ("draft_overrides", models.JSONField(blank=True, default=dict)),
                ("draft_rev", models.PositiveIntegerField(default=1)),
                (
                    "draft_updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "draft_updated_source",
                    models.CharField(
                        choices=[
                            ("customer", "Klant"),
                            ("admin", "Vierlief-team"),
                            ("system", "Systeem"),
                            ("restore", "Hersteld"),
                        ],
                        default="customer",
                        max_length=12,
                    ),
                ),
                ("first_published_at", models.DateTimeField(blank=True, null=True)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="online tot"
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("max_gallery_photos", models.PositiveSmallIntegerField(default=0)),
                (
                    "customer_locked",
                    models.BooleanField(
                        default=False, verbose_name="klant mag tijdelijk niet wijzigen"
                    ),
                ),
                (
                    "lock_reason",
                    models.CharField(blank=True, max_length=200, verbose_name="reden"),
                ),
                ("wizard_step", models.CharField(blank=True, max_length=30)),
                ("event_start", models.DateTimeField(blank=True, null=True)),
                ("rsvp_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="klant",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.templateversion",
                        verbose_name="ontwerpversie (concept)",
                    ),
                ),
            ],
            options={
                "verbose_name": "uitnodiging",
                "verbose_name_plural": "uitnodigingen",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("overrides", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("customer", "Klant"),
                            ("admin", "Vierlief-team"),
                            ("system", "Systeem"),
                            ("restore", "Hersteld"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.templateversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "versie",
                "verbose_name_plural": "versies",
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="draft_base_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="invitations.invitationversion",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="invitations.invitationversion",
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Foto"), ("audio", "Muziek")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=invitations.models.asset_upload_path
                    ),
                ),
                (
                    "file_medium",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=invitations.models.asset_upload_path,
                    ),
                ),
                (
                    "file_thumb",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=invitations.models.asset_upload_path,
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=200)),
                ("content_type", models.CharField(max_length=60)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "upload",
                "verbose_name_plural": "uploads",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_token", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120, verbose_name="naam")),
                ("attending", models.BooleanField(verbose_name="aanwezig")),
                (
                    "party_size",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="aantal personen"
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=list)),
                (
                    "remark",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="toelichting"
                    ),
                ),
                ("edit_token_hash", models.CharField(max_length=64, unique=True)),
                ("edit_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="invitations.invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "aanmelding",
                "verbose_name_plural": "aanmeldingen",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invitation", "client_token"),
                        name="uniq_response_client_token",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invitationversion",
            constraint=models.UniqueConstraint(
                fields=("invitation", "number"), name="uniq_invitation_version"
            ),
        ),
    ]
