# Generated by Django 5.2.17 on 2026-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="draft_updated_source",
            field=models.CharField(
                choices=[
                    ("customer", "Klant"),
                    ("admin", "Vaylia-team"),
                    ("system", "Systeem"),
                    ("restore", "Hersteld"),
                ],
                default="customer",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="invitationversion",
            name="source",
            field=models.CharField(
                choices=[
                    ("customer", "Klant"),
                    ("admin", "Vaylia-team"),
                    ("system", "Systeem"),
                    ("restore", "Hersteld"),
                ],
                max_length=12,
            ),
        ),
    ]
