# Generated by Django 5.2.17 on 2026-09-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_merknaam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("bruiloft", "Bruiloft"),
                    ("verloving", "Verloving"),
                    ("verjaardag", "Verjaardag"),
                    ("jubileum", "Jubileum"),
                    ("babyshower", "Babyshower"),
                    ("zakelijk", "Zakelijk evenement"),
                    ("kerst", "Kerst"),
                ],
                max_length=20,
                verbose_name="gelegenheid",
            ),
        ),
    ]
