# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
import uuid
import wishes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("subject", models.CharField(max_length=140, verbose_name="onderwerp")),
                (
                    "description",
                    models.TextField(max_length=4000, verbose_name="omschrijving"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Ontvangen"),
                            ("in_progress", "In behandeling"),
                            ("proposal", "Voorstel klaar"),
                            ("awaiting_payment", "Akkoord / wacht op betaling"),
                            ("executing", "In uitvoering"),
                            ("done", "Afgerond"),
                            ("closed", "Gesloten"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "proposal_text",
                    models.TextField(blank=True, verbose_name="voorstel"),
                ),
                (
                    "proposal_price_cents",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="prijs voorstel (centen)"
                    ),
                ),
                ("proposal_sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "ai_fit",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "standard",
                                "Lijkt binnen bestaande mogelijkheden te passen",
                            ),
                            ("custom", "Lijkt maatwerk"),
                            ("unclear", "Onduidelijk, eerst navragen"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ai_approach", models.TextField(blank=True)),
                ("ai_questions", models.TextField(blank=True)),
                ("ai_source", models.CharField(blank=True, max_length=20)),
                ("ai_generated_at", models.DateTimeField(blank=True, null=True)),
                ("unread_by_staff", models.BooleanField(default=True)),
                ("unread_by_customer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="klant",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_requests",
                        to="invitations.invitation",
                        verbose_name="uitnodiging",
                    ),
                ),
            ],
            options={
                "verbose_name": "extra wens",
                "verbose_name_plural": "extra wensen",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_staff", models.BooleanField(default=False)),
                (
                    "internal",
                    models.BooleanField(default=False, verbose_name="interne notitie"),
                ),
                ("body", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="wishes.customrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "bericht",
                "verbose_name_plural": "berichten",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=wishes.models.attachment_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=200)),
                ("content_type", models.CharField(max_length=80)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="wishes.customrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="wishes.requestmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "bijlage",
                "verbose_name_plural": "bijlagen",
                "ordering": ["created_at"],
            },
        ),
    ]
