# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        ("wishes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="bestelnummer"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("invitation", "Uitnodiging"), ("custom", "Maatwerk")],
                        default="invitation",
                        max_length=12,
                    ),
                ),
                ("invitation_title", models.CharField(blank=True, max_length=200)),
                ("package_code", models.CharField(blank=True, max_length=50)),
                ("package_name", models.CharField(blank=True, max_length=80)),
                ("features", models.JSONField(blank=True, default=list)),
                ("max_gallery_photos", models.PositiveSmallIntegerField(default=0)),
                ("availability_months", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_cents",
                    models.PositiveIntegerField(verbose_name="totaal (centen)"),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wacht op betaling"),
                            ("paid", "Betaald"),
                            ("cancelled", "Geannuleerd"),
                            ("failed", "Betaling mislukt"),
                            ("expired", "Verlopen"),
                            ("refunded", "Terugbetaald"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "fulfilment_status",
                    models.CharField(
                        choices=[
                            ("none", "Nog niet gestart"),
                            ("processing", "Wordt verwerkt"),
                            ("done", "Afgerond"),
                            ("attention", "Aandacht nodig"),
                        ],
                        default="none",
                        max_length=12,
                        verbose_name="verwerking",
                    ),
                ),
                ("fulfilment_note", models.TextField(blank=True)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("test_mode", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "custom_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="wishes.customrequest",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="klant",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "version_to_publish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="invitations.invitationversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "bestelling",
                "verbose_name_plural": "bestellingen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("unit_price_cents", models.PositiveIntegerField()),
                ("total_cents", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "bestelregel",
                "verbose_name_plural": "bestelregels",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_ref", models.CharField(blank=True, max_length=80)),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "In behandeling"),
                            ("paid", "Betaald"),
                            ("failed", "Mislukt"),
                            ("canceled", "Geannuleerd"),
                            ("expired", "Verlopen"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=40)),
                ("checkout_url", models.URLField(blank=True, max_length=600)),
                ("test_remote_status", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "betaling",
                "verbose_name_plural": "betalingen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_ref", models.CharField(blank=True, max_length=80)),
                ("source", models.CharField(default="webhook", max_length=20)),
                ("remote_status", models.CharField(blank=True, max_length=20)),
                ("outcome", models.CharField(blank=True, max_length=200)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="orders.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "betalingsmelding",
                "verbose_name_plural": "betalingsmeldingen",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_ref", ""), _negated=True),
                fields=("provider", "provider_ref"),
                name="uniq_payment_provider_ref",
            ),
        ),
    ]
